### ISSUE TITLE
Thoughts about moving to spree-contrib

### ISSUE THREAD

**Issue by jspizziri** [spree-contrib/spree_contact_us#47]
What are your thoughts about moving this to spree-contrib?

**Comment by JDutil** [comment]
done

**Comment by jspizziri** [comment]
@JDutil if you'd like you can add me as a contributor so I can tidy some things up without having to bother you.

**Comment by JDutil** [comment]
@jspizziri you should be added now

**Comment by JDutil** [comment]
Thanks
