### ISSUE TITLE
form error translations

### ISSUE THREAD

**Issue by connecticus** [spree-contrib/spree_contact_us#52]
Ok, we have translations for example for spanish. But errors  ("This field is required", "Please enter a valid email address." ) still in english.

**Comment by JDutil** [comment]
You probably either need rails i18n for validations https://github.com/svenfuchs/rails-i18n

**Comment by connecticus** [comment]
Jeff, thank you for answer, I do, but no luck.

**Comment by GraphicDesk** [comment]
I have the same issue... Hot to alter "This field is required" ?
