### ISSUE TITLE
Routing error on spree_contact_us:install

### ISSUE THREAD

**Issue by clebrun** [spree-contrib/spree_contact_us#53]
[Error and Gemfile](https://gist.github.com/clebrun/b43c58437fcea5b88476)

I'm on a clean install with ruby 2.2.2, rails 4.2.2, spree 3.0.3.
pops up for me as soon as I try bundle exec rails g install spree_contact_us:install.

I'm guessing it's because I'm using 3.0.3, but any suggestions would be appreciated.

**Comment by JDutil** [comment]
Use the 3-0-stable branch not a gem release.

gem 'spree_contact_us', github: 'spree-contrib', branch: '3-0-stable'

**Comment by clebrun** [comment]
Thanks, that was it.
